name: devinschaffner
favicon: null
layout_spectrum: 0.29494890850037336
typography_spectrum: 0.5070053862873465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.562378270784393
  lightness: 0.4732737566810101
  saturation: 0.15741632808931172
  rhythmicContrast: 0.47882701363414526
purpose: []
